apiVersion: v1
kind: Secret
metadata:
  name: refit-backend-secret
  namespace: refit-app
type: Opaque
stringData:
  application-secret.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://CHANGE_ME_DATABASE_HOST:5432/refit
        username: CHANGE_ME_DB_USER
        password: CHANGE_ME_DB_PASSWORD

      data:
        redis:
          host: refit-redis-svc
          port: 6379
          password: ""

      security:
        oauth2:
          client:
            registration:
              kakao:
                client-id: CHANGE_ME_KAKAO_CLIENT_ID
                client-secret: CHANGE_ME_KAKAO_CLIENT_SECRET
                redirect-uri: https://dev.re-fit.kr/callback.html
                redirect-uri-local: http://localhost:3000/callback.html
        user:
          name: swagger
          password: CHANGE_ME_SWAGGER_PASSWORD
          roles: ADMIN

      jwt:
        secret: CHANGE_ME_JWT_SECRET
        issuer: re-fit
        access-exp-ms: 1200000
        refresh-exp-ms: 1209600000

      mail:
        host: smtp.gmail.com
        port: 587
        username: CHANGE_ME_EMAIL_USERNAME
        password: CHANGE_ME_EMAIL_PASSWORD
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              connectiontimeout: 5000
              timeout: 5000
              writetimeout: 5000
        test-connection: false

      cloud:
        aws:
          credentials:
            access-key: CHANGE_ME_AWS_ACCESS_KEY
            secret-key: CHANGE_ME_AWS_SECRET_KEY
          region:
            static: ap-northeast-2
          s3:
            bucket: refit-storage-dev
            domain: https://refit-storage-dev.s3.ap-northeast-2.amazonaws.com

    fcm:
      project-id: re-fit-cf52c
      webpush-icon-url: https://refit-storage-dev.s3.ap-northeast-2.amazonaws.com/icons/notifications/atti.png

    kafka:
      bootstrap-servers: refit-kafka-svc:9092
      consumer:
        group-id: refit-backend-dev

    internal:
      api-key: CHANGE_ME_INTERNAL_API_KEY
      api-key-header: X-Internal-Api-Key

    sentry:
      dsn: CHANGE_ME_SENTRY_DSN
