# External Secrets v2.1.0 (chart: external-secrets-2.1.0)
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets --version 2.1.0 -n external-secrets --create-namespace -f external-secrets-values.yaml

installCRDs: true
