apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: refit-ai-external-secret
  namespace: refit-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.envSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: refit/ai
