apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "refit-ai.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "refit-ai.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "refit-ai.fullname" . }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: refit/ai
