apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "refit-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "refit-ai.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httproute.parentRefs }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .name }}
      namespace: {{ .namespace }}
    {{- end }}
  rules:
    {{- range .Values.httproute.rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value | quote }}
        {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - group: ""
          kind: Service
          name: {{ .name | default (include "refit-ai.fullname" $) }}
          port: {{ .port }}
          weight: 1
        {{- end }}
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "refit-ai.fullname" . }}-healthcheck
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "refit-ai.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httproute.parentRefs | nindent 4 }}
  rules:
    - matches:
        - path:
            type: Exact
            value: {{ .Values.healthCheckRoute.path }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "refit-ai.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
