apiVersion: v1
kind: Service
metadata:
  name: refit-backend-svc
  namespace: refit-app
spec:
  selector:
    app: refit-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
