apiVersion: v1
kind: ResourceQuota
metadata:
  name: refit-app-quota
  namespace: refit-app
spec:
  hard:
    requests.memory: "8Gi"
    limits.memory: "11Gi"
    pods: "15"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.memory: "8Gi"
    limits.memory: "16Gi"
    pods: "25"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocd-quota
  namespace: argocd
spec:
  hard:
    requests.memory: "3Gi"
    limits.memory: "6Gi"
    pods: "15"
