apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-tempo
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: monitoring-tempo
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/instance: monitoring-tempo
  endpoints:
    - port: tempo-prom-metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-tempo-headless
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: monitoring-tempo
    app.kubernetes.io/name: tempo
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: monitoring-tempo
    app.kubernetes.io/name: tempo
  ports:
    - name: tempo-prom-metrics
      port: 3200
      protocol: TCP
      targetPort: 3200
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: tempo-otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
