kminion:
  config:
    kafka:
      brokers:
        - b-1.refitkafka.cj233e.c2.kafka.ap-northeast-2.amazonaws.com:9092
        - b-2.refitkafka.cj233e.c2.kafka.ap-northeast-2.amazonaws.com:9092
      clientId: kminion
      tls:
        enabled: false
      sasl:
        enabled: false

    minion:
      consumerGroups:
        enabled: true
        granularity: partition
        scrapeMode: adminApi
        ignoredGroups:
          - console-consumer-.*
      topics:
        enabled: true
      endToEnd:
        enabled: true
        topicManagement:
          enabled: true
          name: kminion-end-to-end
          replicationFactor: 1
        producer:
          requiredAcks: all
        consumer:
          commitSla: 2s
        probeInterval: 10s

    exporter:
      host: 0.0.0.0
      port: 8080

serviceMonitor:
  create: true
  interval: 30s
  scrapeTimeout: 25s
  honorLabels: false
  additionalLabels:
    release: monitoring-prometheus

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  node-role.kubernetes.io/worker: ""
